/* oxlint-disable */
// AUTOGENERATED by vite/content.ts — do not edit

import type { PageEntry } from "@/types";

export const PAGE_PATHS = ["/", "/bar", "/blog", "/blog/content-as-pages", "/explore", "/use"] as const;
export type PagePath = (typeof PAGE_PATHS)[number];

export const PAGES: PageEntry[] = [
  {
    path: "/",
    title: "Daniil Arz",
  },
  {
    path: "/bar",
    title: "Bar",
    description: "Drinks that i like",
  },
  {
    path: "/blog",
    title: "Blog",
  },
  {
    path: "/blog/content-as-pages",
    title: "Контент как страницы сайта",
    date: "2026-08-31",
    duration: "4min",
  },
  {
    path: "/explore",
    title: "Explore",
    description: "Things I want to try",
  },
  {
    path: "/use",
    title: "Use",
    description: "Things I am using",
  },
];
