/* oxlint-disable */
// AUTOGENERATED by vite/content.ts — do not edit

import type { PageEntry } from "@/types";

export const PAGE_PATHS = ["/", "/bar", "/blog", "/blog/content-as-pages", "/explore", "/use"] as const;
export type PagePath = (typeof PAGE_PATHS)[number];

export const PAGES: PageEntry[] = [
  {
    path: "/",
    title: "Daniil Arz",
  },
  {
    path: "/bar",
    title: "Бар",
    description: "Напитки, которые мне нравятся",
  },
  {
    path: "/blog",
    title: "Блог",
  },
  {
    path: "/blog/content-as-pages",
    title: "Контент как страницы сайта",
    date: "2026-08-31",
    duration: "4 мин",
  },
  {
    path: "/explore",
    title: "На заметку",
    description: "Что хочу попробовать",
  },
  {
    path: "/use",
    title: "Рабочее место",
    description: "То, что использую каждый день",
  },
];
