/* oxlint-disable */
// AUTOGENERATED by vite/content-paths.ts — do not edit

export const PAGE_PATHS = ["/", "/bar", "/explore", "/use"] as const;
export type PagePath = (typeof PAGE_PATHS)[number];
