import type { Plugin } from "vite";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { relative } from "node:path";
import { fileToPagePath, isContentFile } from "../src/lib/content/path.ts";

const CONTENT_DIR = "src/content";
const OUTPUT_FILE = "src/lib/content/paths.gen.ts";

function scanContentFiles(root: string = CONTENT_DIR) {
  return readdirSync(root, { recursive: true, encoding: "utf8" })
    .map((entry) => entry.replaceAll("\\", "/"))
    .filter(isContentFile)
    .sort();
}

export function scanPagePaths(root: string = CONTENT_DIR) {
  const byPath = new Map<string, string>();

  for (const file of scanContentFiles(root)) {
    const path = fileToPagePath(file);
    const taken = byPath.get(path);
    if (taken) throw new Error(`Content collision: "${taken}" and "${file}" both map to "${path}"`);
    byPath.set(path, file);
  }

  return [...byPath.keys()].sort();
}

function renderPagePaths(paths: string[]) {
  const literals = paths.map((path) => JSON.stringify(path));

  return (
    `/* oxlint-disable */\n` +
    `// AUTOGENERATED by vite/content-paths.ts — do not edit\n\n` +
    `export const PAGE_PATHS = [${literals.join(", ")}] as const;\n` +
    `export type PagePath = (typeof PAGE_PATHS)[number];\n`
  );
}

function generatePagePaths(root: string = CONTENT_DIR, outputFile: string = OUTPUT_FILE) {
  const content = renderPagePaths(scanPagePaths(root));
  if (existsSync(outputFile) && readFileSync(outputFile, "utf8") === content) return;
  writeFileSync(outputFile, content);
}

function isContentFileEvent(file: string, root: string = CONTENT_DIR) {
  const rel = relative(root, file).replaceAll("\\", "/");
  return !rel.startsWith("..") && isContentFile(rel);
}

function isContentFolder(path: string, root: string = CONTENT_DIR) {
  const rel = relative(root, path).replaceAll("\\", "/");
  return !rel.startsWith("..");
}

export function contentPaths(): Plugin {
  return {
    name: "content-paths",
    buildStart() {
      generatePagePaths();
    },
    configureServer(server) {
      const onFsEvent = (file: string) => {
        if (isContentFileEvent(file)) generatePagePaths();
      };
      server.watcher.on("add", onFsEvent);
      server.watcher.on("unlink", onFsEvent);
      server.watcher.on("unlinkDir", (dir) => {
        if (isContentFolder(dir)) generatePagePaths();
      });
    },
  };
}
