import type { Plugin } from "vite";
import type { Frontmatter, PageEntry } from "../src/types.ts";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { parse } from "yaml";
import { fileToPagePath, isContentFile } from "../src/lib/content/path.ts";

const CONTENT_DIR = "src/content";
const OUTPUT_FILE = "src/lib/content/content.gen.ts";

const BOM = /^\uFEFF/;
const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(\r?\n|$)/;

function readFrontmatter(file: string): Frontmatter {
  const match = FRONTMATTER.exec(readFileSync(file, "utf8").replace(BOM, ""));
  if (!match) throw new Error(`Content page "${file}" has no frontmatter`);

  const frontmatter: Frontmatter = parse(match[1]);
  if (!frontmatter.title) throw new Error(`Content page "${file}" has no title`);

  return frontmatter;
}

export function collectPages(root: string = CONTENT_DIR): PageEntry[] {
  const files = readdirSync(root, { recursive: true, encoding: "utf8" })
    .map((entry) => entry.replaceAll("\\", "/"))
    .filter(isContentFile);

  const takenBy = new Map<string, string>();

  const pages = files.map((file) => {
    const path = fileToPagePath(file);
    const taken = takenBy.get(path);
    if (taken) throw new Error(`Content collision: "${taken}" and "${file}" both map to "${path}"`);

    takenBy.set(path, file);
    return { path, ...readFrontmatter(join(root, file)) };
  });

  return pages.sort((a, b) => a.path.localeCompare(b.path));
}

export function scanPagePaths(root: string = CONTENT_DIR) {
  return collectPages(root).map((page) => page.path);
}

function render(pages: PageEntry[]) {
  const paths = pages.map((page) => JSON.stringify(page.path)).join(", ");

  const entries = pages
    .map((page) => {
      const fields = Object.entries(page)
        .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},\n`)
        .join("");

      return `  {\n${fields}  },\n`;
    })
    .join("");

  return `/* oxlint-disable */
// AUTOGENERATED by vite/content.ts — do not edit

import type { PageEntry } from "@/types";

export const PAGE_PATHS = [${paths}] as const;
export type PagePath = (typeof PAGE_PATHS)[number];

export const PAGES: PageEntry[] = ${entries ? `[\n${entries}]` : "[]"};
`;
}

function generate(root: string = CONTENT_DIR, outputFile: string = OUTPUT_FILE) {
  const output = render(collectPages(root));
  if (existsSync(outputFile) && readFileSync(outputFile, "utf8") === output) return;
  writeFileSync(outputFile, output);
}

function isInsideContent(path: string, root: string = CONTENT_DIR) {
  return !relative(root, path).replaceAll("\\", "/").startsWith("..");
}

export function content(): Plugin {
  return {
    name: "content",
    buildStart() {
      generate();
    },
    configureServer(server) {
      for (const event of ["add", "change", "unlink", "unlinkDir"] as const) {
        server.watcher.on(event, (path) => {
          if (isInsideContent(path)) generate();
        });
      }
    },
  };
}
